apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-crash
  labels:
    app: broken-crash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-crash
  template:
    metadata:
      labels:
        app: broken-crash
    spec:
      containers:
        - name: boom
          image: busybox:1.36
          # わざとすぐ終了する
          command: ["sh", "-c", "echo boom: intentional crash; exit 1"]
