apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-demo
  labels:
    app: healthy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthy-demo
  template:
    metadata:
      labels:
        app: healthy-demo
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
